apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-pvc
  namespace: owncloud-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
  namespace: owncloud-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      containers:
        - name: owncloud
          image: owncloud/server:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: owncloud-config
            - secretRef:
                name: owncloud-secrets
          volumeMounts:
            - name: files-storage
              mountPath: /mnt/data
      volumes:
        - name: files-storage
          persistentVolumeClaim:
            claimName: files-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: owncloud
  namespace: owncloud-namespace
spec:
  selector:
    app: owncloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
