apiVersion: v1
kind: ConfigMap
metadata:
  name: owncloud-config
  namespace: owncloud-namespace
data:
  OWNCLOUD_DOMAIN: "localhost:8080"
  OWNCLOUD_TRUSTED_DOMAINS: "owncloud.almarey.work"
  OWNCLOUD_DB_NAME: "owncloud"
  OWNCLOUD_DB_USERNAME: "owncloud"
  OWNCLOUD_DB_HOST: "mariadb"
  OWNCLOUD_MYSQL_UTF8MB4: "true"
  OWNCLOUD_REDIS_ENABLED: "true"
  OWNCLOUD_REDIS_HOST: "redis"