apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: owncloud-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11  # Confirm this is the desired version
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-secrets  # Ensure this secret exists and contains the MYSQL_ROOT_PASSWORD key
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: owncloud  # Confirm the database name is correct
            - name: MYSQL_USER
              value: owncloud  # Confirm the database user is correct
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-secrets  # Ensure this secret exists and contains the MYSQL_PASSWORD key
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
          args: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]  # Optional: confirm these args are needed for your use case
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc-new  # Ensure this PVC is correctly defined and in a Bound state

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: owncloud-namespace
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
